/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;

import BackEnd.HelperMethods;
//import com.mysql.cj.xdevapi.Statement;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;





/**
 *
 * @author USMAN
 */

public class drop2 extends javax.swing.JFrame {

    /**
     * Creates new form donateFunds
     */
    
    public String data [];

    
    public drop2(String [] x) {
        
        this.data = x;

        initComponents();
        
        
        
        //connection
        try {
            
                        msg.setVisible(false);
            
			Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb" ,"root","abc123");
			java.sql.Statement stmt = c.createStatement();
                        
			ResultSet r = stmt.executeQuery("SELECT gender FROM gender");  
			while(r.next()) {
                                agndr.addItem(r.getString(1));
			}
                        agndr.setSelectedIndex(0);

                        
                        r = stmt.executeQuery("SELECT category FROM category");  
			while(r.next()) {
                                atype.addItem(r.getString(1));
			}
                        atype.setSelectedIndex(0);
                        
                        
                        r = stmt.executeQuery("SELECT color FROM color");  
			while(r.next()) {
                                clr.addItem(r.getString(1));
			}
                        clr.setSelectedIndex(0);
                        
                        
                        r = stmt.executeQuery("SELECT disease FROM disease");  
			while(r.next()) {
                                ds.addItem(r.getString(1));
			}

//                        r = stmt.executeQuery("SELECT breed FROM cat_breed,breed where breed.breed_id = cat_breed.breed_id");  
//			while(r.next()) {
//                                brd.addItem(r.getString(1));
//			}
//                         brd.setSelectedIndex(0);
                        
	   } 
            
            catch (Exception e) {
                
			System.out.println(e.getMessage());
		}
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        msg = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        photoframe1 = new javax.swing.JLabel();
        photo2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        form = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        clr = new javax.swing.JComboBox<>();
        h = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        nkn = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        w = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        atype = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        confirm1 = new javax.swing.JButton();
        aage = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        agndr = new javax.swing.JComboBox<>();
        brd = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        ds = new javax.swing.JComboBox<>();
        photo = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        formchart = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1457, 835));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        msg.setOpaque(false);
        msg.setLayout(null);

        jButton10.setBackground(new java.awt.Color(51, 153, 0));
        jButton10.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Goodbye");
        jButton10.setBorder(null);
        jButton10.setBorderPainted(false);
        jButton10.setDefaultCapable(false);
        jButton10.setFocusPainted(false);
        jButton10.setFocusable(false);
        jButton10.setRequestFocusEnabled(false);
        jButton10.setRolloverEnabled(false);
        jButton10.setVerifyInputWhenFocusTarget(false);
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton10MouseEntered(evt);
            }
        });
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        msg.add(jButton10);
        jButton10.setBounds(160, 520, 220, 40);

        jLabel33.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 24)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Thank you");
        msg.add(jLabel33);
        jLabel33.setBounds(200, 280, 210, 70);

        jLabel32.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Say a last Goodbye");
        msg.add(jLabel32);
        jLabel32.setBounds(190, 460, 180, 50);

        jLabel31.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("until he finds a new loving home");
        msg.add(jLabel31);
        jLabel31.setBounds(170, 430, 220, 23);

        jLabel30.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("We promise to keep your pet safe and happy");
        msg.add(jLabel30);
        jLabel30.setBounds(140, 410, 280, 20);

        jLabel7.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Your Pet is in safe hands ");
        msg.add(jLabel7);
        jLabel7.setBounds(160, 340, 240, 28);

        photoframe1.setBackground(new java.awt.Color(255, 255, 255));
        photoframe1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/photo.png"))); // NOI18N
        photoframe1.setMaximumSize(new java.awt.Dimension(0, 0));
        photoframe1.setMinimumSize(new java.awt.Dimension(0, 0));
        photoframe1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                photoframe1MouseEntered(evt);
            }
        });
        msg.add(photoframe1);
        photoframe1.setBounds(164, 60, 200, 210);

        photo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/noPicture.png"))); // NOI18N
        msg.add(photo2);
        photo2.setBounds(170, 70, 190, 190);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/form chart.PNG"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        msg.add(jLabel4);
        jLabel4.setBounds(70, 10, 398, 580);

        getContentPane().add(msg);
        msg.setBounds(430, 140, 500, 600);

        form.setOpaque(false);
        form.setLayout(null);

        jPanel5.setEnabled(false);
        jPanel5.setFocusable(false);
        jPanel5.setOpaque(false);

        clr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clrjPanel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clrjPanel4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                clrjTextField1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clrjTextField1MouseReleased(evt);
            }
        });

        h.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hMouseClicked(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(51, 51, 51));
        jLabel11.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Nickname (opt)");

        jLabel13.setBackground(new java.awt.Color(51, 51, 51));
        jLabel13.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Gender");

        nkn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nknMouseClicked(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(51, 51, 51));
        jLabel14.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Color");

        jLabel15.setBackground(new java.awt.Color(51, 51, 51));
        jLabel15.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Height (cms)");

        jLabel16.setBackground(new java.awt.Color(51, 51, 51));
        jLabel16.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Weight (kgs)");

        w.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wMouseClicked(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(51, 51, 51));
        jLabel17.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Type");

        atype.setBackground(new java.awt.Color(255, 255, 255));
        atype.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                atypeItemStateChanged(evt);
            }
        });
        atype.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                atypejPanel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                atypejPanel4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                atypejTextField1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                atypejTextField1MouseReleased(evt);
            }
        });

        jLabel18.setBackground(new java.awt.Color(51, 51, 51));
        jLabel18.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("disease (if any)");

        confirm1.setBackground(new java.awt.Color(51, 153, 0));
        confirm1.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        confirm1.setForeground(new java.awt.Color(255, 255, 255));
        confirm1.setText("Confirm");
        confirm1.setBorderPainted(false);
        confirm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm1ActionPerformed(evt);
            }
        });

        aage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aageMouseClicked(evt);
            }
        });

        jLabel24.setBackground(new java.awt.Color(51, 51, 51));
        jLabel24.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Age");

        agndr.setBackground(new java.awt.Color(255, 255, 255));
        agndr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                agndrjPanel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                agndrjPanel4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                agndrjTextField1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                agndrjTextField1MouseReleased(evt);
            }
        });

        brd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                brdMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                brdjPanel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                brdjPanel4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                brdjTextField1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                brdjTextField1MouseReleased(evt);
            }
        });

        jLabel25.setBackground(new java.awt.Color(51, 51, 51));
        jLabel25.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Breed");

        ds.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none" }));
        ds.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dsjPanel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dsjPanel4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dsjTextField1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                dsjTextField1MouseReleased(evt);
            }
        });

        photo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "upload from computer" }));

        jLabel12.setBackground(new java.awt.Color(51, 51, 51));
        jLabel12.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Photo");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel18)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel15))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel24)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel17))
                                    .addGap(1, 1, 1)))
                            .addGap(5, 5, 5)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel14)
                        .addComponent(jLabel25))
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(atype, 0, 232, Short.MAX_VALUE)
                    .addComponent(nkn)
                    .addComponent(aage)
                    .addComponent(agndr, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(h)
                    .addComponent(clr, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(brd, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(w, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ds, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(photo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(confirm1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nkn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agndr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(h, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(w, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(ds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(clr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(brd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(photo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(confirm1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        form.add(jPanel5);
        jPanel5.setBounds(0, 70, 380, 540);

        jLabel19.setBackground(new java.awt.Color(59, 179, 0));
        jLabel19.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("                Animal Details");
        jLabel19.setOpaque(true);
        jLabel19.setPreferredSize(new java.awt.Dimension(49, 16));
        form.add(jLabel19);
        jLabel19.setBounds(10, 10, 390, 50);

        formchart.setBackground(new java.awt.Color(51, 51, 51));
        formchart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/form chart0.png"))); // NOI18N
        formchart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formchartMouseEntered(evt);
            }
        });
        form.add(formchart);
        formchart.setBounds(10, -40, 400, 740);

        getContentPane().add(form);
        form.setBounds(890, 120, 430, 660);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jButton2.setBackground(new java.awt.Color(51, 153, 0));
        jButton2.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Home");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setDefaultCapable(false);
        jButton2.setFocusPainted(false);
        jButton2.setFocusable(false);
        jButton2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton2MouseMoved(evt);
            }
        });
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(51, 153, 0));
        jButton4.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Adopt Animal");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setDefaultCapable(false);
        jButton4.setFocusPainted(false);
        jButton4.setFocusable(false);
        jButton4.setRequestFocusEnabled(false);
        jButton4.setRolloverEnabled(false);
        jButton4.setVerifyInputWhenFocusTarget(false);
        jButton4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jButton4MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton4MouseMoved(evt);
            }
        });
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton4MouseExited(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(51, 153, 0));
        jButton3.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Drop Animal");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setFocusPainted(false);
        jButton3.setFocusable(false);
        jButton3.setRequestFocusEnabled(false);
        jButton3.setRolloverEnabled(false);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(51, 153, 0));
        jButton5.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Find Animal");
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setFocusPainted(false);
        jButton5.setFocusable(false);
        jButton5.setRequestFocusEnabled(false);
        jButton5.setRolloverEnabled(false);
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton5MouseExited(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(51, 153, 0));
        jButton7.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Report Incident");
        jButton7.setBorder(null);
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setFocusPainted(false);
        jButton7.setFocusable(false);
        jButton7.setRequestFocusEnabled(false);
        jButton7.setRolloverEnabled(false);
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton7MouseExited(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(51, 153, 0));
        jButton6.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Contact Us");
        jButton6.setBorder(null);
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setFocusPainted(false);
        jButton6.setFocusable(false);
        jButton6.setRequestFocusEnabled(false);
        jButton6.setRolloverEnabled(false);
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton6MouseExited(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(51, 153, 0));
        jButton8.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Donate Fund");
        jButton8.setBorder(null);
        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jButton8.setFocusPainted(false);
        jButton8.setFocusable(false);
        jButton8.setRequestFocusEnabled(false);
        jButton8.setRolloverEnabled(false);
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton8MouseExited(evt);
            }
        });
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 490, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1457, 57);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jButton9.setBackground(new java.awt.Color(51, 153, 0));
        jButton9.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 12)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Murphy's Animal Shelter");
        jButton9.setBorder(null);
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.setDefaultCapable(false);
        jButton9.setFocusPainted(false);
        jButton9.setFocusable(false);
        jButton9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton9MouseMoved(evt);
            }
        });
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton9MouseExited(evt);
            }
        });
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 1482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(-10, 810, 1480, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/drop.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(1457, 835));
        jLabel1.setMinimumSize(new java.awt.Dimension(1457, 835));
        jLabel1.setPreferredSize(new java.awt.Dimension(1457, 835));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1460, 840);

        setSize(new java.awt.Dimension(1457, 834));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9MouseMoved

    private void jButton9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseEntered
        jButton9.setContentAreaFilled(true);
        jButton9.setOpaque(false);
        
    }//GEN-LAST:event_jButton9MouseEntered

    private void jButton9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseExited
        
        jButton9.setContentAreaFilled(false);
        jButton9.setOpaque(false);
    }//GEN-LAST:event_jButton9MouseExited

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/drop.jpeg")));
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        
    }//GEN-LAST:event_jLabel1MouseExited

    private void formchartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formchartMouseEntered
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/drop2.jpeg")));
    }//GEN-LAST:event_formchartMouseEntered

    private void jButton2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseMoved

    }//GEN-LAST:event_jButton2MouseMoved

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered

        jButton2.setContentAreaFilled(true);
        jButton2.setOpaque(false);
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited

        jButton2.setContentAreaFilled(false);
        jButton2.setOpaque(false);
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseDragged

    }//GEN-LAST:event_jButton4MouseDragged

    private void jButton4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseMoved

    }//GEN-LAST:event_jButton4MouseMoved

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered

        jButton4.setContentAreaFilled(true);
        jButton4.setOpaque(false);
    }//GEN-LAST:event_jButton4MouseEntered

    private void jButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseExited

        jButton4.setContentAreaFilled(false);
        jButton4.setOpaque(false);
    }//GEN-LAST:event_jButton4MouseExited

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered

        jButton3.setContentAreaFilled(true);
        jButton3.setOpaque(false);
    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited

    }//GEN-LAST:event_jButton3MouseExited

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseEntered

        jButton5.setContentAreaFilled(true);
        jButton5.setOpaque(false);
    }//GEN-LAST:event_jButton5MouseEntered

    private void jButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseExited

        jButton5.setContentAreaFilled(false);
        jButton5.setOpaque(false);
    }//GEN-LAST:event_jButton5MouseExited

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseEntered

        jButton7.setContentAreaFilled(true);
        jButton7.setOpaque(false);
    }//GEN-LAST:event_jButton7MouseEntered

    private void jButton7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseExited

        jButton7.setContentAreaFilled(false);
        jButton7.setOpaque(false);
    }//GEN-LAST:event_jButton7MouseExited

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseEntered

        jButton6.setContentAreaFilled(true);
        jButton6.setOpaque(false);
    }//GEN-LAST:event_jButton6MouseEntered

    private void jButton6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseExited

        jButton6.setContentAreaFilled(false);
        jButton6.setOpaque(false);
    }//GEN-LAST:event_jButton6MouseExited

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseEntered

        jButton8.setContentAreaFilled(true);
        jButton8.setOpaque(false);
    }//GEN-LAST:event_jButton8MouseEntered

    private void jButton8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseExited

        jButton8.setContentAreaFilled(false);
        jButton8.setOpaque(false);
    }//GEN-LAST:event_jButton8MouseExited

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void clrjPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clrjPanel4MouseEntered

    }//GEN-LAST:event_clrjPanel4MouseEntered

    private void clrjPanel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clrjPanel4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_clrjPanel4MouseExited

    private void clrjTextField1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clrjTextField1MousePressed

    }//GEN-LAST:event_clrjTextField1MousePressed

    private void clrjTextField1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clrjTextField1MouseReleased

    }//GEN-LAST:event_clrjTextField1MouseReleased

    private void hMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hMouseClicked

        h.setText("");
        h.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_hMouseClicked

    private void nknMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nknMouseClicked

        nkn.setText("");
        nkn.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_nknMouseClicked

    private void wMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wMouseClicked

        w.setText("");
        w.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_wMouseClicked

    private void atypejPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atypejPanel4MouseEntered

    }//GEN-LAST:event_atypejPanel4MouseEntered

    private void atypejPanel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atypejPanel4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_atypejPanel4MouseExited

    private void atypejTextField1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atypejTextField1MousePressed

    }//GEN-LAST:event_atypejTextField1MousePressed

    private void atypejTextField1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atypejTextField1MouseReleased

    }//GEN-LAST:event_atypejTextField1MouseReleased

    String path = "";
    
    private void confirm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm1ActionPerformed

        int errors= 0;
        
        
        
        if (aage.getText().length() > 0 && HelperMethods.isNumber(aage.getText()) != false)
        {
              if (Integer.parseInt(aage.getText()) > 120 || Integer.parseInt(aage.getText()) < 1) 
              {
                  errors++;
                  aage.setForeground(new java.awt.Color(255, 0, 0));
              }
              else 
              {
              //get value
              }
             
        }
        else
        {
            aage.setText("Please enter an age");
             errors++;
             aage.setForeground(new java.awt.Color(255, 0, 0));
        }
        
        
        //get gender
        
        
        
        if (h.getText().length() != 0 && HelperMethods.isNumber(h.getText()) == true)
        {
            if (Integer.parseInt(h.getText()) < 10 || Integer.parseInt(h.getText()) > 250)
            {
                errors++;
             h.setForeground(new java.awt.Color(255, 0, 0));
            }
            else
            {
                //get value
            }
        }
        else
        {
            h.setText("Please enter a height");
             errors++;
             h.setForeground(new java.awt.Color(255, 0, 0));
        }
        
        
        
        
        if (w.getText().length() != 0 && HelperMethods.isNumber(w.getText()) == true)
        {
            if (Integer.parseInt(w.getText()) < 1 || Integer.parseInt(w.getText()) > 250)
            {
                errors++;
             w.setForeground(new java.awt.Color(255, 0, 0));
            }
            else
            {
                //get value
            }
        }
        else
        {
            w.setText("Please enter weight");
             errors++;
             w.setForeground(new java.awt.Color(255, 0, 0));
        }
        
        
        File selectedFile = null;
           
        if (photo.getSelectedIndex() == 1 && errors == 0)
        {
             JFileChooser fileChooser = new JFileChooser();
             fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
             int result = fileChooser.showOpenDialog(this);
             if (result == JFileChooser.APPROVE_OPTION) {
                 selectedFile = fileChooser.getSelectedFile();
                 path = selectedFile.getAbsolutePath();
                 
             }
        }
        
        
        if (errors == 0)
        {
            //establish connection
            try {
			Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb" ,"root","abc123");

			java.sql.Statement stmt = c.createStatement();
                        String pid = "";
                        //insertion of person data
                        int npid = -1;
                        if (data.length > 2)
                        {
                            
                            stmt.executeUpdate("insert into address ( address , city_id) values ('" + data[7] + "'," + data[8] + ")");
                            ResultSet rs = stmt.executeQuery("SELECT id FROM address ORDER BY id DESC LIMIT 1");
                            rs.next();
                            int adcnt = Integer.parseInt(rs.getString(1));
                            
                        
                            
                            stmt.executeUpdate("insert into person (first_name , last_name , age , dob , cnic , email , address_id , gender_id) values ( '"  + data[0] + "','" + data[1] + "'," + data[2] + ",'" +  data[3] + "','" +  data[5] + "','" + data[6] + "'," + adcnt + "," +  data[4] + ")");
                            
                            rs = stmt.executeQuery("SELECT id FROM person ORDER BY id DESC LIMIT 1");
                            rs.next();
                            int prsnId = Integer.parseInt(rs.getString(1));
                            npid = prsnId;
                            pid = prsnId + "";
                            stmt.executeUpdate("insert into dropper (person_id) values (" + prsnId + ")");
                            
                            stmt.executeUpdate("insert into phone (phone_no , person_id) values ('" + data[9] + "'," + prsnId + ")");
                        }
                        
                        //insertion of animal data
                            ResultSet rs = stmt.executeQuery("SELECT breed_id FROM breed where breed = '" + brd.getSelectedItem().toString()+ "'");
                            rs.next();
                            int breedId = Integer.parseInt(rs.getString(1));
        
                            
                            int agnder = agndr.getSelectedIndex()+1;
                            int color = clr.getSelectedIndex()+1;
                            int tpe = atype.getSelectedIndex()+1;
                           
                         
                            if (photo.getSelectedIndex() == 1)
                            {
                                InputStream is = new FileInputStream (new File(path));
                                stmt.executeUpdate("insert into animal (nickname , weight , height , age , gender_id , color_id , category_id , breed_id , photo) values ('" + nkn.getText() +"',"+ w.getText() +","+ h.getText() +","+ aage.getText() +","+ agnder +","+ color +","+ tpe +","+ breedId + "," + null +  ")");
                                rs = stmt.executeQuery("SELECT collar_id FROM animal ORDER BY collar_id DESC LIMIT 1");
                                String aid = "1";
                                if (rs.next())
                                {
                                    aid = rs.getString(1);
                                }
                                
                                
                                PreparedStatement ps = c.prepareStatement("update animal set photo = ? where collar_id = ?");
                                ps.setBlob(1,is);
                                ps.setString(2,aid );
                                ps.executeUpdate();
                            
                            }
                            else
                            {
                            stmt.executeUpdate("insert into animal (nickname , weight , height , age , gender_id , color_id , category_id , breed_id , photo) values ('" + nkn.getText() +"',"+ w.getText() +","+ h.getText() +","+ aage.getText() +","+ agnder +","+ color +","+ tpe +","+ breedId + "," + selectedFile +  ")");
                            }
                            
                            
                            rs = stmt.executeQuery("SELECT collar_id FROM animal ORDER BY collar_id DESC LIMIT 1");
                            rs.next();
                            int clrId = Integer.parseInt(rs.getString(1));
                            
                            System.out.println("Animal added.");
                            
                            
                        //insertion of disease data
                            if (ds.getSelectedIndex() != 0)
                            {
                                rs = stmt.executeQuery("SELECT report_id FROM medical_report ORDER BY report_id DESC LIMIT 1");
                                int rptId;
                                if (rs.next())
                                {
                                rptId = Integer.parseInt(rs.getString(1)+1);
                                }
                                else
                                {
                                 rptId = 1;       
                                }
                                stmt.executeUpdate("insert into medical_report (report_id,collar_id ,disease_id) values (" + rptId  + "," + clrId + "," + (ds.getSelectedIndex()+1)  +")");
                                stmt.executeUpdate("insert into to_be_treated (report_id) values (" + rptId  + ")");
                                
                            }
                            
                        //relation between animal and person
                        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
                            Date date = new Date();
                            
                        if (npid != -1)
                        {
                            stmt.executeUpdate("insert into animal_has_dropper (collar_id , dropper_id, dropping_reason_id , date ) values (" + clrId + "," + npid + "," + data[10] +",'"+ formatter.format(date) +"')");
                        }
                        else
                        {
                            stmt.executeUpdate("insert into animal_has_dropper (collar_id , dropper_id, dropping_reason_id , date ) values (" + clrId + "," + data[0] + "," + data[1] +",'"+ formatter.format(date) +"')");
                        }
                    
                        
                        msg.setVisible(true);
                        form.setVisible(false);
                       
                        
                        ResultSet r = stmt.executeQuery("select * from animal order by collar_id desc limit 1");
                        r.next();
                        if (r.getBlob("photo") != null)
                                {
                                byte [] im = r.getBytes("photo");
                                ImageIcon ima = new ImageIcon (im);
                                Image imag = ima.getImage();
                                Image image = imag.getScaledInstance(photo.getWidth(), photo.getHeight(), Image.SCALE_SMOOTH);
                                ImageIcon myphoto = new ImageIcon (image);
                                photo2.setIcon(myphoto);
                               
                                photo2.setBounds(170, 70, 190, 190);
                                
                                }
                                else
                                {
                                    photo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/noPicture.png")));
                                }
                 
                        
		} 
            
            catch (Exception e) {
                
			System.out.println(e.getMessage());
		}
            
        }
        
        
        
        
        
    }//GEN-LAST:event_confirm1ActionPerformed

    private void aageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aageMouseClicked

        aage.setText("");
        aage.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_aageMouseClicked

    private void agndrjPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agndrjPanel4MouseEntered

    }//GEN-LAST:event_agndrjPanel4MouseEntered

    private void agndrjPanel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agndrjPanel4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_agndrjPanel4MouseExited

    private void agndrjTextField1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agndrjTextField1MousePressed

    }//GEN-LAST:event_agndrjTextField1MousePressed

    private void agndrjTextField1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agndrjTextField1MouseReleased

    }//GEN-LAST:event_agndrjTextField1MouseReleased

    private void brdjPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brdjPanel4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_brdjPanel4MouseEntered

    private void brdjPanel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brdjPanel4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_brdjPanel4MouseExited

    private void brdjTextField1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brdjTextField1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_brdjTextField1MousePressed

    private void brdjTextField1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brdjTextField1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_brdjTextField1MouseReleased

    private void dsjPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dsjPanel4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_dsjPanel4MouseEntered

    private void dsjPanel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dsjPanel4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_dsjPanel4MouseExited

    private void dsjTextField1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dsjTextField1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_dsjTextField1MousePressed

    private void dsjTextField1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dsjTextField1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_dsjTextField1MouseReleased

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
    
        
        new adoptAnimal ().setVisible(true);
        this.setVisible(false);
        this.dispose();
        
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        
        
        new home ().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        
        
        new FindAnimal ().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked

        new ReportIncident ().setVisible(true); 
        this.setVisible(false);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        
       
        new donateFunds ().setVisible(true);
         this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        
       
        new contactUs ().setVisible(true);
         this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        // TODO add your handling code here:
        
        new contactUs ().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton9MouseClicked

    private void dsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dsMouseClicked
        
        
        
        
    }//GEN-LAST:event_dsMouseClicked

    private void brdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brdMouseClicked
       
 
        
    }//GEN-LAST:event_brdMouseClicked

    private void atypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_atypeItemStateChanged
        
         try {
            
            
                Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb" ,"root","abc123");
                java.sql.Statement stmt = c.createStatement();

                ResultSet r;
                brd.removeAllItems();
                
                

                if (atype.getSelectedIndex() == 0)
                {

                    r = stmt.executeQuery("SELECT breed FROM cat_breed natural join breed");  
                                while(r.next()) {
                                        brd.addItem(r.getString(1));
                                }
                                 brd.setSelectedIndex(0);
                }
                
                else if (atype.getSelectedIndex() == 1)
                {

                    r = stmt.executeQuery("SELECT breed FROM dog_breed natural join breed ");  
                                while(r.next()) {
                                        brd.addItem(r.getString(1));
                                }
                                 brd.setSelectedIndex(0);
                    
                }
                
                else if (atype.getSelectedIndex() == 2)
                {

                    r = stmt.executeQuery("SELECT breed FROM rabbit_breed natural join breed ");  
                                while(r.next()) {
                                        brd.addItem(r.getString(1));
                                }
                                 brd.setSelectedIndex(0);
                }
                
                else if (atype.getSelectedIndex() == 3)
                {

                    r = stmt.executeQuery("SELECT breed FROM horse_breed natural join breed ");  
                                while(r.next()) {
                                        brd.addItem(r.getString(1));
                                }
                                 brd.setSelectedIndex(0);
                }
                
                else 
                {
                    
                    r = stmt.executeQuery("SELECT breed FROM donkey_breed,breed where breed.breed_id = donkey_breed.breed_id");  
                                while(r.next()) {
                                        brd.addItem(r.getString(1));
                                }
                                 brd.setSelectedIndex(0);

                }
                
                brd.setSelectedIndex(0);
                        
	   } 
            
            catch (Exception e) {
                
			System.out.println(e.getMessage());
		}
        
        
       
    }//GEN-LAST:event_atypeItemStateChanged

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

        msg.setVisible(false);
        form.setVisible(true);
        
        new drop1 ().setVisible(true);
        this.dispose();
        this.setVisible(false);

    }//GEN-LAST:event_jButton10ActionPerformed

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/drop2.jpeg")));
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/drop.jpeg")));
    }//GEN-LAST:event_jLabel4MouseExited

    private void photoframe1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_photoframe1MouseEntered
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/drop2.jpeg")));
    }//GEN-LAST:event_photoframe1MouseEntered

    private void jButton10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseEntered
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/drop2.jpeg")));
    }//GEN-LAST:event_jButton10MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(drop2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(drop2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(drop2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(drop2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aage;
    private javax.swing.JComboBox<String> agndr;
    private javax.swing.JComboBox<String> atype;
    private javax.swing.JComboBox<String> brd;
    private javax.swing.JComboBox<String> clr;
    private javax.swing.JButton confirm1;
    private javax.swing.JComboBox<String> ds;
    private javax.swing.JPanel form;
    private javax.swing.JLabel formchart;
    private javax.swing.JTextField h;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel msg;
    private javax.swing.JTextField nkn;
    private javax.swing.JComboBox<String> photo;
    private javax.swing.JLabel photo2;
    private javax.swing.JLabel photoframe1;
    private javax.swing.JTextField w;
    // End of variables declaration//GEN-END:variables
}
