-- MySQL Script generated by MySQL Workbench
-- Sat Dec 14 15:28:19 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`gender`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`gender` (
  `id` INT NOT NULL,
  `gender` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`color` (
  `id` INT NOT NULL,
  `color` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `id` INT NOT NULL,
  `category` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`breed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`breed` (
  `breed_id` INT NOT NULL,
  PRIMARY KEY (`breed_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`animal` (
  `collar_id` INT NOT NULL AUTO_INCREMENT,
  `nickname` VARCHAR(45) NULL,
  `weight` DECIMAL(4,1) NULL,
  `height` INT NULL,
  `age` INT NULL,
  `photo` BLOB NULL,
  `gender_id` INT NOT NULL,
  `color_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  `eye_color_id` INT NOT NULL,
  `breed_id` INT NOT NULL,
  PRIMARY KEY (`collar_id`),
  INDEX `fk_animal_gender_idx` (`gender_id` ASC) ,
  INDEX `fk_animal_color1_idx` (`color_id` ASC) ,
  INDEX `fk_animal_category1_idx` (`category_id` ASC) ,
  INDEX `fk_animal_color2_idx` (`eye_color_id` ASC) ,
  INDEX `fk_animal_breed1_idx` (`breed_id` ASC) ,
  CONSTRAINT `fk_animal_gender`
    FOREIGN KEY (`gender_id`)
    REFERENCES `mydb`.`gender` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_animal_color1`
    FOREIGN KEY (`color_id`)
    REFERENCES `mydb`.`color` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_animal_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `mydb`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_animal_color2`
    FOREIGN KEY (`eye_color_id`)
    REFERENCES `mydb`.`color` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_animal_breed1`
    FOREIGN KEY (`breed_id`)
    REFERENCES `mydb`.`breed` (`breed_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cat_breed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cat_breed` (
  `breed_id` INT NOT NULL,
  PRIMARY KEY (`breed_id`),
  CONSTRAINT `fk_cat_breed_breed1`
    FOREIGN KEY (`breed_id`)
    REFERENCES `mydb`.`breed` (`breed_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`donkey_breed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`donkey_breed` (
  `breed_id` INT NOT NULL,
  PRIMARY KEY (`breed_id`),
  CONSTRAINT `fk_donkey_breed_breed1`
    FOREIGN KEY (`breed_id`)
    REFERENCES `mydb`.`breed` (`breed_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dog_breed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dog_breed` (
  `breed_id` INT NOT NULL,
  PRIMARY KEY (`breed_id`),
  CONSTRAINT `fk_dog_breed_breed1`
    FOREIGN KEY (`breed_id`)
    REFERENCES `mydb`.`breed` (`breed_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rabbit_breed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rabbit_breed` (
  `breed_id` INT NOT NULL,
  PRIMARY KEY (`breed_id`),
  CONSTRAINT `fk_rabbit_breed_breed1`
    FOREIGN KEY (`breed_id`)
    REFERENCES `mydb`.`breed` (`breed_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`horse_breed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`horse_breed` (
  `breed_id` INT NOT NULL,
  PRIMARY KEY (`breed_id`),
  CONSTRAINT `fk_horse_breed_breed1`
    FOREIGN KEY (`breed_id`)
    REFERENCES `mydb`.`breed` (`breed_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`country` (
  `id` INT NOT NULL,
  `country` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`city` (
  `id` INT NOT NULL,
  `city` VARCHAR(45) NULL,
  `postal_code` VARCHAR(45) NULL,
  `country_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_city_country1_idx` (`country_id` ASC) ,
  CONSTRAINT `fk_city_country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `mydb`.`country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`address` (
  `id` INT NOT NULL,
  `address` VARCHAR(45) NULL,
  `permanent_address` VARCHAR(45) NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_address_city1_idx` (`city_id` ASC) ,
  CONSTRAINT `fk_address_city1`
    FOREIGN KEY (`city_id`)
    REFERENCES `mydb`.`city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`person` (
  `id` INT NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `age` INT NULL,
  `dob` VARCHAR(10) NULL,
  `cnic` VARCHAR(15) NULL,
  `email` VARCHAR(45) NULL,
  `address_id` INT NOT NULL,
  `gender_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cnic_UNIQUE` (`cnic` ASC) ,
  INDEX `fk_person_address1_idx` (`address_id` ASC) ,
  INDEX `fk_person_gender1_idx` (`gender_id` ASC) ,
  CONSTRAINT `fk_person_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `mydb`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_person_gender1`
    FOREIGN KEY (`gender_id`)
    REFERENCES `mydb`.`gender` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`adopter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`adopter` (
  `monthly_income` INT NULL,
  `person_id` INT NOT NULL,
  PRIMARY KEY (`person_id`),
  CONSTRAINT `fk_adopter_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `mydb`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`donator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`donator` (
  `amount` INT NULL,
  `person_id` INT NOT NULL,
  PRIMARY KEY (`person_id`),
  CONSTRAINT `fk_donator_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `mydb`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dropper`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dropper` (
  `person_id` INT NOT NULL,
  PRIMARY KEY (`person_id`),
  CONSTRAINT `fk_dropper_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `mydb`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`disease`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`disease` (
  `id` INT NOT NULL,
  `disease` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Medical_report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Medical_report` (
  `animal_collar_id` INT NULL,
  `disease_id` INT NULL,
  `report_id` VARCHAR(45) NOT NULL,
  INDEX `fk_animal_has_disease_disease1_idx` (`disease_id` ASC) ,
  INDEX `fk_animal_has_disease_animal1_idx` (`animal_collar_id` ASC) ,
  PRIMARY KEY (`report_id`),
  CONSTRAINT `fk_animal_has_disease_animal1`
    FOREIGN KEY (`animal_collar_id`)
    REFERENCES `mydb`.`animal` (`collar_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_animal_has_disease_disease1`
    FOREIGN KEY (`disease_id`)
    REFERENCES `mydb`.`disease` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`to_be_treated`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`to_be_treated` (
  `treatement_cost` INT NULL,
  `report_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`report_id`),
  CONSTRAINT `fk_to_be_treated_Medical_report1`
    FOREIGN KEY (`report_id`)
    REFERENCES `mydb`.`Medical_report` (`report_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`under_treatement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`under_treatement` (
  `start_date` VARCHAR(45) NULL,
  `report_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`report_id`),
  CONSTRAINT `fk_under_treatement_Medical_report1`
    FOREIGN KEY (`report_id`)
    REFERENCES `mydb`.`Medical_report` (`report_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`treated`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`treated` (
  `start_date` VARCHAR(45) NULL,
  `end_date` VARCHAR(45) NULL,
  `treatement_cost` INT NULL,
  `report_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`report_id`),
  CONSTRAINT `fk_treated_Medical_report1`
    FOREIGN KEY (`report_id`)
    REFERENCES `mydb`.`Medical_report` (`report_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`incident_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`incident_type` (
  `id` INT NOT NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dropping_reason`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dropping_reason` (
  `id` INT NOT NULL,
  `reason` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`incident_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`incident_status` (
  `id` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`incident`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`incident` (
  `incident_id` INT NOT NULL AUTO_INCREMENT,
  `location` VARCHAR(45) NULL,
  `reported_date` VARCHAR(45) NULL,
  `time` VARCHAR(45) NULL,
  `reporter_contact` VARCHAR(45) NULL,
  `incident_type_id` INT NOT NULL,
  `incident_status_id` INT NOT NULL,
  PRIMARY KEY (`incident_id`),
  INDEX `fk_incident_incident_type1_idx` (`incident_type_id` ASC) ,
  INDEX `fk_incident_incident_status1_idx` (`incident_status_id` ASC) ,
  CONSTRAINT `fk_incident_incident_type1`
    FOREIGN KEY (`incident_type_id`)
    REFERENCES `mydb`.`incident_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_incident_incident_status1`
    FOREIGN KEY (`incident_status_id`)
    REFERENCES `mydb`.`incident_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`untreatable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`untreatable` (
  `report_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`report_id`),
  CONSTRAINT `fk_untreatable_Medical_report1`
    FOREIGN KEY (`report_id`)
    REFERENCES `mydb`.`Medical_report` (`report_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`phone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`phone` (
  `phone_no` VARCHAR(45) NOT NULL,
  `person_id` INT NOT NULL,
  PRIMARY KEY (`person_id`, `phone_no`),
  CONSTRAINT `fk_phone_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `mydb`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`animal_has_adopter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`animal_has_adopter` (
  `animal_collar_id` INT NOT NULL,
  `adopter_id` INT NOT NULL,
  `date` VARCHAR(45) NULL,
  PRIMARY KEY (`animal_collar_id`, `adopter_id`),
  INDEX `fk_animal_has_adopter_adopter1_idx` (`adopter_id` ASC) ,
  INDEX `fk_animal_has_adopter_animal1_idx` (`animal_collar_id` ASC) ,
  CONSTRAINT `fk_animal_has_adopter_animal1`
    FOREIGN KEY (`animal_collar_id`)
    REFERENCES `mydb`.`animal` (`collar_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_animal_has_adopter_adopter1`
    FOREIGN KEY (`adopter_id`)
    REFERENCES `mydb`.`adopter` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`animal_has_dropper`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`animal_has_dropper` (
  `animal_collar_id` INT NOT NULL,
  `dropper_id` INT NOT NULL,
  `dropping_reason_id` INT NOT NULL,
  `date` VARCHAR(45) NULL,
  PRIMARY KEY (`animal_collar_id`, `dropper_id`),
  INDEX `fk_animal_has_dropper_dropper1_idx` (`dropper_id` ASC) ,
  INDEX `fk_animal_has_dropper_animal1_idx` (`animal_collar_id` ASC) ,
  INDEX `fk_animal_has_dropper_dropping_reason1_idx` (`dropping_reason_id` ASC) ,
  CONSTRAINT `fk_animal_has_dropper_animal1`
    FOREIGN KEY (`animal_collar_id`)
    REFERENCES `mydb`.`animal` (`collar_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_animal_has_dropper_dropper1`
    FOREIGN KEY (`dropper_id`)
    REFERENCES `mydb`.`dropper` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_animal_has_dropper_dropping_reason1`
    FOREIGN KEY (`dropping_reason_id`)
    REFERENCES `mydb`.`dropping_reason` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
